# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jhonatan/Documents/basys/modulacion/tesis_v1/tesis_v1.srcs/sources_1/ip/product/product.xci
# IP: The module: 'product' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jhonatan/Documents/basys/modulacion/tesis_v1/tesis_v1.srcs/sources_1/ip/product/product_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'product'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Jhonatan/Documents/basys/modulacion/tesis_v1/tesis_v1.srcs/sources_1/ip/product/product.xci
# IP: The module: 'product' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jhonatan/Documents/basys/modulacion/tesis_v1/tesis_v1.srcs/sources_1/ip/product/product_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'product'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
