# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/system_top_level_0_11.xci
# IP: The module: 'system_top_level_0_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/product/product.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==product || ORIG_REF_NAME==product} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/acumulador/acumulador.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==acumulador || ORIG_REF_NAME==acumulador} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/suma/suma.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==suma || ORIG_REF_NAME==suma} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/my_rest/my_rest.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_rest || ORIG_REF_NAME==my_rest} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/my_multiplicador/my_multiplicador.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_multiplicador || ORIG_REF_NAME==my_multiplicador} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/product_sdr/product_sdr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==product_sdr || ORIG_REF_NAME==product_sdr} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/system_top_level_0_11.xci
# IP: The module: 'system_top_level_0_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/product/product.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==product || ORIG_REF_NAME==product} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/acumulador/acumulador.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==acumulador || ORIG_REF_NAME==acumulador} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/suma/suma.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==suma || ORIG_REF_NAME==suma} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/my_rest/my_rest.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_rest || ORIG_REF_NAME==my_rest} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/my_multiplicador/my_multiplicador.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_multiplicador || ORIG_REF_NAME==my_multiplicador} -quiet] -quiet

# IP: c:/Users/Henry/Documents/TesisV4.0-RedPitaya_1-GFDM/TesisV4.0-RedPitaya_1/Pitaya/redpitaya_guide-master/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_top_level_0_11/src/product_sdr/product_sdr.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==product_sdr || ORIG_REF_NAME==product_sdr} -quiet] -quiet
