# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/product_sdr/product_sdr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==product_sdr || ORIG_REF_NAME==product_sdr} -quiet] -quiet
