webtalk_init -webtalk_dir C:/Users/Henry/Documents/TesisV4.0-RedPitaya_1/TesisV4.0-RedPitaya_1/Programas_VHDL/tesis_v1/tesis_v1/tesis_v1.sim/sim_1/behav/xsim/xsim.dir/test_toplevel_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun  3 22:37:12 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ffeb09a7-28a9-4a22-a662-fda47199bd01" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4c3bf5f1d25149f6b6b074ecf4c23b6c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "55" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 3 PRO 4350G with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "75 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "14.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "48720_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1684362569 -regid "" -xml C:/Users/Henry/Documents/TesisV4.0-RedPitaya_1/TesisV4.0-RedPitaya_1/Programas_VHDL/tesis_v1/tesis_v1/tesis_v1.sim/sim_1/behav/xsim/xsim.dir/test_toplevel_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Henry/Documents/TesisV4.0-RedPitaya_1/TesisV4.0-RedPitaya_1/Programas_VHDL/tesis_v1/tesis_v1/tesis_v1.sim/sim_1/behav/xsim/xsim.dir/test_toplevel_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Henry/Documents/TesisV4.0-RedPitaya_1/TesisV4.0-RedPitaya_1/Programas_VHDL/tesis_v1/tesis_v1/tesis_v1.sim/sim_1/behav/xsim/xsim.dir/test_toplevel_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
