# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jhonatan/Documents/basys/modulacion/tesis_v1/tesis_v1.srcs/sources_1/ip/my_rest/my_rest.xci
# IP: The module: 'my_rest' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jhonatan/Documents/basys/modulacion/tesis_v1/tesis_v1.srcs/sources_1/ip/my_rest/my_rest_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_rest'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Jhonatan/Documents/basys/modulacion/tesis_v1/tesis_v1.srcs/sources_1/ip/my_rest/my_rest.xci
# IP: The module: 'my_rest' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jhonatan/Documents/basys/modulacion/tesis_v1/tesis_v1.srcs/sources_1/ip/my_rest/my_rest_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_rest'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
